[FIX] hr: prevent error when loading scenario data
Currently, an error occurs when loading scenario data after user deleted
administration department.

Steps to replicate:
- Install `hr` and open `Employees > Departments`.
- Delete the `Administration` department.
- Open Employees, Delete all the employees and Click `load sample data'.

Error:
```
ValueError: External ID not found in the system: hr.dep_administration
ParseError: while parsing /home/odoo/src/odoo/saas-19.3/addons/hr/data/scenarios/hr_scenario.xml:114, somewhere inside
<record id='employee_mw' model='hr.employee' forcecreate='1'>
            <field name='active'>True</field...
```

Cause:
- As the user deleted the administration department before the scenario data was
  loaded the error occurs from [here].
- In the previous version, this error did not occur because, starting from
  `saas-18.4`, scenario data is loaded through a server action [1]. In earlier
  versions, the scenario data was loaded along with the demo data through the
  settings instead. During demo data loading, any errors are converted into
  warnings, so no error is raised.

Solution:
- Prevented error from occurring when reference is not found. Since these fields
  are not required, they can safely remain empty.

[1]: https://github.com/odoo/odoo/blob/9400393a13d238404c9797a906ee11b6afcc761e/addons/hr/views/hr_employee_views.xml#L567

[here]: https://github.com/odoo/odoo/blob/b3d0cf09b491f180d6b6d654026497cc7de6731d/addons/hr/data/scenarios/hr_scenario.xml#L124

sentry-7441124574

closes odoo/odoo#274606

Signed-off-by: Mélanie Peyrat (mepe) <mepe@odoo.com>