[FIX] sale_margin: prevent error on selecting a section template in SO.
Steps to Reproduce:
1. Install the sale_margin module.
2. Sales > Configuration > Templates.
3. Create a template with type 'Section', and add a section line.
4. Create a Sales Order, click Add Section, and select the created template.

Error:
ValueError: Expected singleton: res.currency()

Cause:
The _prepare_order_line_values() method mistakenly stores the converted
purchase price in the currency_id field instead of purchase_price. When these
values are used to create a sales order line, leaving currency_id unset. - [1]
As a result, the onchange later fails when it expects a valid currency. - [2]

Fix:
Pass the correct field value of purchase_price instead of currency_id.

[1]: https://github.com/odoo/odoo/blob/f2f656371f81683ee3fe558932df53a2d0c5d374/addons/sale_management/models/sale_order_template.py#L346-L350
[2]: https://github.com/odoo/odoo/blob/f2f656371f81683ee3fe558932df53a2d0c5d374/addons/sale_margin/models/sale_order_line.py#L76

opw-6347869

closes odoo/odoo#274458

X-original-commit: e42d417f6b5153caa1a7c2c45c59c9a41bac1681
Signed-off-by: Victor Feyens (vfe) <vfe@odoo.com>