[FIX] pos_sale: prevent crash on archived attribute when settling SO
When a product attribute line is used in a confirmed sale order, Odoo
archives it (active=False) instead of deleting it when removed from the
product template.  If the corresponding product.attribute record is also
archived, settling that sale order in PoS crashes with:

  TypeError: Cannot read properties of undefined (reading 'create_variant')

opw-6315766

closes odoo/odoo#271778

Signed-off-by: David Monnom (moda) <moda@odoo.com>